
# .air.toml

[build]
  cmd = "go build -o tmp/main ." # Adjust this if your main file is in a different directory
  bin = "tmp/main"

[log]
  time = true
  color = true
  level = "info"

[watch]
  dirs = ["cmd", "handlers", "internals", "models", "routers", "config"]
  ignore = ["tmp"]

